FROM node:22-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./

COPY svelte.config.js ./

RUN npm ci

COPY . .
RUN npm run build

RUN npm prune --omit=dev

FROM node:22-slim AS runner

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .

EXPOSE 5000

ENV NODE_ENV=production

CMD ["node", "build"]
