name: Edpacca CI
run-name: ${{ github.head_ref }} ${{ github.sha }}
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    test-build-deploy:
        name: test build and deploy
        if: '!github.event.pull_request.draft'
        concurrency: ci-${{github.ref}}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                ref: ${{ github.head_ref }}
                fetch-depth: 1

            - name: Set up node
              uses: actions/setup-node@v3
              with:
                node-version: 16
            
            - name: Install Dependencies
              run: npm install
            
            - name: Check
              run: |
                touch .env
                echo "GH_URL=https://dummy.com" >> .env
                echo "GH_REPO_TOKEN=123ABC456" >> .env
                echo "PUBLIC_STRAVA_CURRENT=7259" >> .env
                echo "PUBLIC_STRAVA_LAST_UPDATED=09-08-23" >> .env
                echo "PUBLIC_STRAVA_TARGET=10000" >> .env
                echo "PUBLIC_STRAVA_GOAL_YEAR=2023" >> .env
                echo "PUBLIC_STRAVA_GOAL='10km elevation'" >> .env
                npm run check
            
            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: svelte-kit
                branch: gh-pages
        
